In [1]:
import pandas as pd
import unicodedata

In [2]:
weibo = pd.read_csv(r"data\raw\weibo_wordfreq.release_UTF-8.txt", sep ='\t', header = None, names = ['word', 'count'], encoding = "utf-8-sig")

In [3]:
print(weibo.shape)
weibo.head(10)

(328257, 2)

  word      count
0    的  207824558
1    我  107133693
2    了   91700393
3    你   60717518
4    是   47904895
5    ~   43240132
6    在   35443976
7    有   31564816
8    不   29309227
9    个   25983977

In [4]:
news = pd.read_csv(r"data\raw\news_wordfreq.release_UTF-8.txt", sep ='\t', header = None, names = ['word', 'count'], encoding = "utf-8-sig")

In [5]:
print(news.shape)
news.head(10)

(406779, 2)

  word     count
0    的  94016071
1    了  21442735
2    在  20947026
3    和  17382588
4    是  13621418
5    有   7481110
6    个   7293582
7    上   6835585
8    中   6834149
9    为   6620942

In [6]:
news[news['word'].str.len() == 1]['word'].apply(lambda x: not '\u4e00' <= x <= '\u9fff').sum()

np.int64(1094)

In [7]:
def has_control(s):
    return any(unicodedata.category(c) in ('Cc', 'Cf') for c in s)

weibo = weibo[~weibo['word'].apply(has_control)]

In [8]:
weibo_symbol_count = weibo[weibo['word'].str.len() == 1]['word'].apply(lambda x: not '\u4e00' <= x <= '\u9fff').sum()
print(weibo_symbol_count)

1552

In [9]:
subtlex = pd.read_csv(r"data\raw\SUBTLEX_CH_131210_CE.utf8", sep = "\t", encoding = "utf-8-sig")
print(subtlex.shape)
subtlex[['Word', 'WCount']].head(10)

(99121, 15)

  Word   WCount
0    的  1682530
1    我  1682285
2    你  1329424
3    是   947807
4    了   946365
5    不   689161
6    在   429766
7    他   397653
8   我们   371696
9    好   334698

In [10]:
print("Weibo duplicates:", weibo['word'].duplicated().sum())
print("News duplicates:", news['word'].duplicated().sum())
print("SUBTLEX-CH duplicates:", subtlex['Word'].duplicated().sum())

Weibo duplicates: 2
News duplicates: 0
SUBTLEX-CH duplicates: 388

In [11]:
dupes = weibo[weibo['word'].duplicated(keep = False)]

In [12]:
for w in dupes['word'].unique():
    print(repr(w), [hex(ord(c)) for c in w])

'0%' ['0x30', '0x25']
'1100%' ['0x31', '0x31', '0x30', '0x30', '0x25']

In [13]:
weibo_clean = (
    weibo.assign(word=weibo['word'].astype(str).apply(lambda x: unicodedata.normalize('NFKC', x)))
         .groupby('word', as_index=False)['count'].sum()
)

news_clean = (
    news.assign(word=news['word'].astype(str).apply(lambda x: unicodedata.normalize('NFKC', x)))
        .groupby('word', as_index=False)['count'].sum()
)

subtlex_clean = (
    subtlex.assign(word=subtlex['Word'].astype(str).apply(lambda x: unicodedata.normalize('NFKC', x)))
           .groupby('word', as_index=False)['WCount'].sum()
           .rename(columns={'WCount': 'count'})
)

In [14]:
print("Weibo remaining dupes:", weibo_clean['word'].duplicated().sum())
print("News remaining dupes:", news_clean['word'].duplicated().sum())
print("SUBTLEX remaining dupes:", subtlex_clean['word'].duplicated().sum())

Weibo remaining dupes: 0
News remaining dupes: 0
SUBTLEX remaining dupes: 0

In [15]:
import numpy as np

total_tokens = {
    'weibo': weibo_clean['count'].sum(),
    'news': news_clean['count'].sum(),
    'subtlex': subtlex_clean['count'].sum()
}

weibo_clean['zipf_weibo'] = np.log10((weibo_clean['count'] / total_tokens['weibo']) * 1_000_000_000)
news_clean['zipf_news'] = np.log10((news_clean['count'] / total_tokens['news']) * 1_000_000_000)
subtlex_clean['zipf_subtlex'] = np.log10((subtlex_clean['count'] / total_tokens['subtlex']) * 1_000_000_000)

In [16]:
hsk_master = pd.read_csv(r"data\raw\hsk_vocab_cleaned.xls")
hsk_master.head(10)

,hsk_level,no_in_level,word,pinyin,part_of_speech,english
0,1,1,爱,ài,verb,to love
1,1,2,八,bā,number,eight
2,1,3,爸爸,bàba,noun,dad
3,1,4,吧,ba,auxiliary,"particle indicating suggestion, confirmation, ..."
4,1,5,白天,báitiān,noun,daytime
5,1,6,百,bǎi,number,hundred
6,1,7,半,bàn,number|adverb,"half; (half, semi-)"
7,1,8,包子,bāozi,noun,steamed stuffed bun
8,1,9,杯子,bēizi,noun,"cup, glass"
9,1,10,本,běn,classifier,measure word for books

In [17]:
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:password@localhost:3306/?charset=utf8mb4")

with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS hsk_corpus_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"))

engine = create_engine("mysql+pymysql://root:password@localhost:3306/hsk_corpus_db?charset=utf8mb4")

hsk_master.to_sql('hsk_master', con=engine, if_exists='replace', index=False)
subtlex_clean[['word', 'count', 'zipf_subtlex']].to_sql('subtlex_freq', con=engine, if_exists='replace', index=False)
weibo_clean[['word', 'count', 'zipf_weibo']].to_sql('weibo_freq', con=engine, if_exists='replace', index=False)
news_clean[['word', 'count', 'zipf_news']].to_sql('news_freq', con=engine, if_exists='replace', index=False)

print("All 4 staging tables successfully loaded into MySQL.")

All 4 staging tables successfully loaded into MySQL.